server:
  port: 9092
spring:
  application:
    name: spring-cloud-sofa-drm
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:               jdbc:mysql://148.70.150.51:3306/sofa
    username:           root
    password:           luori5&1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9966/eureka/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false






