server:
  port: 9093
spring:
  application:
    name: spring-cloud-sofa-file-api
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9966/eureka/







