server:
  port: 80
spring:
  application:
    name: spring-cloud-sofa-gate
  cloud:
    gateway:
      routes:
        -      id:  spring-cloud-sofa-auth
               uri: lb://spring-cloud-sofa-auth
               predicates:
                 - Path= /api/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9966/eureka/







