server:
  port: 80
spring:
  cloud:
    gateway:
      routes:
        - id:  spring-cloud-sofa-auth
          uri: lb://spring-cloud-sofa-auth
          predicates:
            - Path= /api/auth/**

  application:
    name: spring-cloud-sofa-gate
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9966/eureka/







