spring:
  application:
    name: cloud-center
server:
  port: 9966

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:9966/eureka/